
- name: Setting up jenkins
  hosts: 127.0.0.1
  connection: local
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Downloading jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0755'

    - name: Import rpm key for package
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
        state: present

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: install the latest version of java
      yum:
        name: java-1.8.0-openjdk
        state: latest

    - name: install the latest version of jenkins
      yum:
        name: jenkins
        state: latest

    - name: start jenkins
      service:
        name: jenkins
        state: started



